platforms:
  - id:     MISEQ_I100_5M_PE300
    name:   "MiSeq i100 5M (2x300)"
    output: "3 Gb"

  - id:     MISEQ_I100_25M_PE300
    name:   "MiSeq i100 25M (2x300)"
    output: "15 Gb"

  - id:     MISEQ_I100_50M_PE300
    name:   "MiSeq i100 50M (2x300)"
    output: "30 Gb"

  - id:     MISEQ_I100_5M_PE150
    name:   "MiSeq i100 5M (2x150)"
    output: "1.5 Gb"

  - id:     MISEQ_I100_25M_PE150
    name:   "MiSeq i100 25M (2x150)"
    output: "7.5 Gb"

  - id:     MISEQ_I100_50M_PE150
    name:   "MiSeq i100 50M (2x150)"
    output: "15 Gb"

  - id:     MISEQ_I100_100M_PE150
    name:   "MiSeq i100 100M (2x150)"
    output: "30 Gb"

  - id:     MISEQ_I100_25M_SE100
    name:   "MiSeq i100 25M (1x100)"
    output: "2.5 Gb"

  - id:     MISEQ_I100_50M_SE100
    name:   "MiSeq i100 50M (1x100)"
    output: "5 Gb"

  - id:     MISEQ_I100_100M_SE100
    name:   "MiSeq i100 100M (1x100)"
    output: "10 Gb"

  # MinION yield is time‑dependent, so keep a base line plus the rate
  - id: MINION
    name: "MinION FLO-MIN114"
    output: "15 Gb"
    bp_per_minute: 3472222
